#!/usr/bin/env bash
# this script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line

n=0
while [ $n -le 10 ]
do
	if [ $n -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
		((n++))
done
