#!/usr/bin/env bash
# this script loops from 1 to 10 and displays different messages based on the iteration number

n=0
while [ $n -lt 10 ]
do
	if [ $n -eq 3 ]

		echo "bad luck"
	elif [ $n -eq 7 ]
		echo "good luck"
	else
		echo "Best School"
	fi
	((n++))
done
