#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows superstitious messages for specific iterations.

n=0
while [ $n -le 20 ]
do
	case $n in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	*)
		echo "$n"
		;;
	esac

	((n++))
done

