#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows superstitious messages for specific iterations.

n=0
while [ $n -le 19 ]
do
	case $n in
	3)
		echo "$n"
		echo "bad luck from China"
		;;
	8)
		echo "$n"
		echo "bad luck from Japan"
		;;
	16)
		echo "$n"
		echo "bad luck from Italy"
		;;
	*)
		echo "$n"
		;;
	esac

	((n++))
done

