#!/usr/bin/env bash
# Script for reloading Gunicorn without service interruption

# Gracefully reload Gunicorn
pgrep gunicorn | xargs -I {} kill -HUP {}

# Ensure a newline at the end of the file
echo ""

